// <auto-generated />
using System;
using AspTemplate.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspTemplate.Migrations
{
    [DbContext(typeof(EtdbContext))]
    partial class EtdbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspTemplate.Context.Bus", b =>
                {
                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("BusId")
                        .HasName("PK__Bus__6A0F60B57855F72B");

                    b.ToTable("Bus");
                });

            modelBuilder.Entity("AspTemplate.Context.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("BasePrice")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("From")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasDefaultValue("");

                    b.Property<string>("To")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasDefaultValue("");

                    b.HasKey("RouteId")
                        .HasName("PK__Route__80979B4D4283D226");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("AspTemplate.Context.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("SeatId")
                        .HasName("PK__Seat__311713F3B50CBDEE");

                    b.HasIndex("BusId");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("AspTemplate.Context.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("From")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("To")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TicketId")
                        .HasName("PK__Ticket__712CC60766A37313");

                    b.HasIndex("SeatId");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("AspTemplate.Context.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("TripId")
                        .HasName("PK__Trip__51DC713EBA3E0D21");

                    b.HasIndex("RouteId");

                    b.ToTable("Trip");
                });

            modelBuilder.Entity("AspTemplate.Context.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasDefaultValue("");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasDefaultValue("");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasDefaultValue("");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4C9F281741");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AspTemplate.Context.Seat", b =>
                {
                    b.HasOne("AspTemplate.Context.Bus", "Bus")
                        .WithMany("Seat")
                        .HasForeignKey("BusId")
                        .IsRequired()
                        .HasConstraintName("FK__Seat__BusId__4AB81AF0");

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("AspTemplate.Context.Ticket", b =>
                {
                    b.HasOne("AspTemplate.Context.Seat", "Seat")
                        .WithMany("Ticket")
                        .HasForeignKey("SeatId")
                        .IsRequired()
                        .HasConstraintName("FK__Ticket__SeatId__5070F446");

                    b.HasOne("AspTemplate.Context.Trip", "Trip")
                        .WithMany("Ticket")
                        .HasForeignKey("TripId")
                        .IsRequired()
                        .HasConstraintName("FK__Ticket__TripId__4F7CD00D");

                    b.HasOne("AspTemplate.Context.User", "User")
                        .WithMany("Ticket")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Ticket__UserId__5165187F");

                    b.Navigation("Seat");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AspTemplate.Context.Trip", b =>
                {
                    b.HasOne("AspTemplate.Context.Route", "Route")
                        .WithMany("Trip")
                        .HasForeignKey("RouteId")
                        .IsRequired()
                        .HasConstraintName("FK__Trip__RouteId__45F365D3");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("AspTemplate.Context.Bus", b =>
                {
                    b.Navigation("Seat");
                });

            modelBuilder.Entity("AspTemplate.Context.Route", b =>
                {
                    b.Navigation("Trip");
                });

            modelBuilder.Entity("AspTemplate.Context.Seat", b =>
                {
                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("AspTemplate.Context.Trip", b =>
                {
                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("AspTemplate.Context.User", b =>
                {
                    b.Navigation("Ticket");
                });
#pragma warning restore 612, 618
        }
    }
}
